Complete Show marker from server data, filter marker near the polyline
2022-solution-challenge/Navi-FE pull request #13
Opened 2022-03-24 14:11 UTC by pell13

2022-03-24 14:30 UTC, pell13 commented on lib/navi/mapDest.dart
> +                visible: false))) //개선사항 : 현재 가까이 있지 않을때(isMarkerNearPath가 false일때) null을 넣으면 뻑나서 비어 있는 마커를 넣었다. 근데 안 넣는 방법은 없을까?
이부분은 where을 쓰는 게 더 나을 것 같네요 ㅠ

2022-03-25 12:56 UTC, hyojaeKwon requested changes
그 debug print꼭 필요한거 아니면 지워만 주세용

2022-03-25 12:56 UTC, hyojaeKwon commented on lib/navi/accident_marker.dart
> +  debugPrint('===========call APIS, ${GetAccidentList().getAccident().runtimeType}==========');
오류 안나면 디버그 프린트 지워주세요 ㅠㅠ 햇갈려서

2022-03-25 13:45 UTC, pell13 commented on lib/navi/accident_marker.dart
> +  debugPrint('===========call APIS, ${GetAccidentList().getAccident().runtimeType}==========');
몇개 지웠뜸~

2022-03-25 13:48 UTC, hyojaeKwon approved these changes
b

2022-03-25 13:48 UTC, merged